# Generated by Django 5.1.7 on 2025-04-20 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Название должно содержать минимум 3 символа'), django.core.validators.MaxLengthValidator(100, 'Название не должно превышать 100 символов')]),
        ),
    ]
